name: Docs Build (main)
on:
  push:
    branches: [main]
  pull_request:
      branches: [ main ]
      paths:
        - 'docs/**'
        - '.github/workflows/build-docs*.yml'
permissions:
  contents: write
jobs:
  docs:
    name: Generate Website
    runs-on: ubuntu-latest
    env:
      SPHINX_GITHUB_CHANGELOG_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Install OS dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libfreetype6-dev libportmidi-dev

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: '3.14'

      - name: Install dependencies
        run: uv sync --group docs

      # TODO: eliminate all warnings and add -W flag to fail at warnings
      - name: Build
        run: uv run sphinx-build -b dirhtml -v docs _build

      - name: Move 404
        run: mv _build/404/index.html _build/404.html

      - name: Update 404 links
        run: uv run python docs/scripts/move_404.py _build/404.html

      - name: Remove .doctrees
        run: rm -r _build/.doctrees

      - name: Upload to GitHub Pages
        if: github.event_name == 'push'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: _build
          target-folder: main
          clean: false
