name: build & test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    paths:
      - 'pyproject.toml'
      - 'setup.py'
      - '.github/workflows/**'
      - 'highway_env/**'
      - 'tests/**'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]

    steps:
    - uses: actions/checkout@v4
    - name: Install OS dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y pkg-config libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libfreetype6-dev libportmidi-dev
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: uv sync --group test
    - name: Test with pytest
      run: uv run pytest --cov=./ --cov-report=xml
